kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/ainasawa/Personals/sessions-component"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-pv-pod
  labels:
    app: task-pv-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-pv-pod
  template:
    metadata:
      labels:
        app: task-pv-pod
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
              name: "mongodb"
        - name: golang-app
          image: nginx
          # command: ["go", "run", "/usr/share/nginx/html/main.go"]
          ports:
            - containerPort: 3000
              name: "golangport"
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: task-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: haystackservice
spec:
  type: NodePort
  selector:
    app: task-pv-pod
  ports:
  - name: mongo-port
    port: 27017
    nodePort: 30069
  - name: sessions-port
    port: 80
    nodePort: 30070

  