kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/nicolas/kubernetes/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: task-pv-pod
  labels:
    app: task-pv-pod
spec:
  replicas: 2
  selector:
    app: task-pv-pod
  template:
    metadata:
      labels:
        app: task-pv-pod
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
           claimName: task-pv-claim
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
              name: "mongodb"
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: task-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: haystackservice
spec:
  type: NodePort
  selector:
    name: task-pv-prod
  ports:
  - name: mport
    protocol: TCP
    port: 27017
    nodePort: 30069